project_name: zeabur

before:
  hooks:
    - make mock
    - go mod tidy
    - go generate ./...

builds:
  - id: "zeabur"
    main: ./cmd
    binary: "zeabur"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - name_template: "zeabur_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: binary
    id: "binary"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  use: github
  filters:
    exclude:
      - "^test:"
      - "^Merge pull request"

release:
  extra_files:
    - glob: "README.md"

brews:
  - name: cli
    repository:
      owner: zeabur
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    homepage: "https://zeabur.com"
    description: "Zeabur's official command line tool"

scoops:
  - url_template: "https://github.com/zeabur/cli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    bucket:
      owner: zeabur
      name: cli
    homepage: "https://zeabur.com"
    description: "Zeabur's official command line tool"
    repository:
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
