project_name: cli

before:
  hooks:
    - make mock
    - go mod tidy
    - go generate ./...

builds:
  - id: "zeabur"
    main: ./cmd
    binary: "zeabur"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - name_template: "zeabur_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: binary
    id: "binary"
  - name_template: "zeabur_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: zip
    id: "zip"

checksum:
  name_template: "checksums.txt"

changelog:
  use: github
  filters:
    exclude:
      - "^test:"
      - "^Merge pull request"

release:
  extra_files:
    - glob: "README.md"

brews:
  - ids: ["zip"]
    repository:
      owner: zeabur
      name: homebrew-tap
    homepage: "https://zeabur.com"
    description: "Zeabur's official command line tool"

scoops:
- ids: ["zip"]
  url_template: "https://github.com/zeabur/cli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  bucket:
    owner: zeabur
    name: cli
  homepage: "https://zeabur.com"
  description: "Zeabur's official command line tool"
