project_name: zeabur

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: "zeabur"
    main: ./cmd
    binary: "zeabur"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - name_template: "zeabur_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: binary
    id: "binary"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  use: github
  filters:
    exclude:
      - "^test:"
      - "^Merge pull request"

release:
  extra_files:
    - glob: "README.md"
